// scripts/seed-shops.js
const { db, generateId, getTimestamp } = require("./src/config/firebase.config");

const seedShops = async () => {
  console.log("🚀 Starting shops seed...");

  const shops = [
    // Nairobi Area
    {
      id: "shop_nbi_001",
      name: "Green Leaf Agrovet Nairobi",
      address: "Tom Mboya Street, CBD",
      location: "Nairobi CBD",
      latitude: -1.286389,
      longitude: 36.817223,
      phone: "+254712345678",
      email: "info@greenleafagrovet.co.ke",
      category: "Agricultural Supplies",
      description:
        "Complete farm input supplier with certified seeds and fertilizers. Open 7 days a week.",
      rating: 4.7,
      reviewCount: 156,
      openingHours: "Mon-Sat: 7:30 AM - 7:00 PM, Sun: 8:00 AM - 5:00 PM",
      website: "https://greenleafagrovet.co.ke",
      distance: 0.5,
      imageUrl:
        "https://images.unsplash.com/photo-1589923186741-b7d59d6b2c4c?w=800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      services: ["Delivery", "Expert Advice", "Bulk Discounts"],
      paymentMethods: ["Cash", "MPesa", "Credit Card"],
      ...getTimestamp(),
    },
    {
      id: "shop_nbi_002",
      name: "Farmers Choice Agrovet",
      address: "River Road, Gikomba",
      location: "Nairobi",
      latitude: -1.276389,
      longitude: 36.837223,
      phone: "+254723456789",
      email: "sales@farmerschoice.co.ke",
      category: "Agricultural Supplies",
      description:
        "Specializing in poultry feeds, veterinary drugs, and farming equipment.",
      rating: 4.5,
      reviewCount: 89,
      openingHours: "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 8:00 AM - 4:00 PM",
      distance: 1.2,
      imageUrl:
        "https://images.unsplash.com/photo-1560493676-04071c5f467b?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      services: ["Free Delivery within CBD", "Technical Support"],
      ...getTimestamp(),
    },
    {
      id: "shop_nbi_003",
      name: "Ushindi Seeds & Fertilizers",
      address: "Ngong Road, Adams Arcade",
      location: "Nairobi",
      latitude: -1.306389,
      longitude: 36.787223,
      phone: "+254734567890",
      category: "Seeds & Fertilizers",
      description:
        "Authorized dealer for certified seeds from Kenya Seed Company and fertilizer suppliers.",
      rating: 4.8,
      reviewCount: 203,
      openingHours: "Mon-Sat: 8:00 AM - 6:30 PM",
      distance: 2.5,
      imageUrl:
        "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Kiambu Area
    {
      id: "shop_kbu_001",
      name: "Thika Farmers Agrovet",
      address: "General Kago Road, Thika",
      location: "Kiambu",
      latitude: -1.039167,
      longitude: 37.072778,
      phone: "+254745678901",
      category: "Agricultural Supplies",
      description:
        "Serving farmers in Central Kenya with quality farm inputs since 2010.",
      rating: 4.6,
      reviewCount: 134,
      openingHours: "Mon-Sat: 7:00 AM - 6:00 PM",
      distance: 25.3,
      imageUrl:
        "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_kbu_002",
      name: "Fresh Produce Suppliers",
      address: "Kikuyu Town, Kiambu Road",
      location: "Kiambu",
      latitude: -1.246667,
      longitude: 36.663333,
      phone: "+254756789012",
      category: "General Store",
      description:
        "Your one-stop shop for farm inputs, tools, and fresh produce.",
      rating: 4.3,
      reviewCount: 78,
      openingHours: "Daily: 6:30 AM - 7:00 PM",
      distance: 18.7,
      imageUrl:
        "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Nakuru Area
    {
      id: "shop_nkr_001",
      name: "Rift Valley Farm Supplies",
      address: "Moi Avenue, Nakuru CBD",
      location: "Nakuru",
      latitude: -0.303099,
      longitude: 36.080025,
      phone: "+254767890123",
      email: "info@riftvalleyfarms.co.ke",
      category: "Farm Machinery",
      description:
        "Leading supplier of farm machinery, irrigation systems, and heavy equipment in Rift Valley.",
      rating: 4.9,
      reviewCount: 267,
      openingHours: "Mon-Fri: 8:00 AM - 5:00 PM, Sat: 8:00 AM - 1:00 PM",
      website: "https://riftvalleyfarms.co.ke",
      distance: 140.5,
      imageUrl:
        "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      services: ["Equipment Rental", "Maintenance Services", "Installation"],
      ...getTimestamp(),
    },
    {
      id: "shop_nkr_002",
      name: "Menengai Agrovet",
      address: "Lanet, Nakuru",
      location: "Nakuru",
      latitude: -0.278056,
      longitude: 36.149722,
      phone: "+254778901234",
      category: "Veterinary Services",
      description: "Specialized veterinary drugs and animal health products.",
      rating: 4.4,
      reviewCount: 92,
      openingHours: "Mon-Sat: 8:00 AM - 6:00 PM",
      distance: 138.2,
      imageUrl:
        "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Eldoret Area
    {
      id: "shop_eld_001",
      name: "Eldoret Grain & Fertilizer Co.",
      address: "Uganda Road, Eldoret",
      location: "Uasin Gishu",
      latitude: 0.514444,
      longitude: 35.278889,
      phone: "+254789012345",
      email: "orders@eldoretgrain.co.ke",
      category: "Grains & Fertilizers",
      description:
        "Major distributor of fertilizers, cereals, and grain storage solutions.",
      rating: 4.7,
      reviewCount: 189,
      openingHours: "Mon-Fri: 7:30 AM - 5:30 PM, Sat: 8:00 AM - 4:00 PM",
      distance: 280.7,
      imageUrl:
        "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Kisumu Area
    {
      id: "shop_ksm_001",
      name: "Lake Basin Agrovet",
      address: "Kondele, Kisumu",
      location: "Kisumu",
      latitude: -0.102281,
      longitude: 34.761712,
      phone: "+254790123456",
      category: "Fisheries & Aquaculture",
      description:
        "Specializing in fish feeds, pond liners, and aquaculture equipment.",
      rating: 4.6,
      reviewCount: 112,
      openingHours: "Mon-Sat: 8:00 AM - 6:00 PM",
      distance: 320.4,
      imageUrl:
        "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Mombasa Area
    {
      id: "shop_mbs_001",
      name: "Coastal Farm Supplies",
      address: "Moi Avenue, Mombasa",
      location: "Mombasa",
      latitude: -4.043477,
      longitude: 39.668205,
      phone: "+254701234567",
      category: "Irrigation & Greenhouse",
      description:
        "Suppliers of irrigation systems, greenhouse materials, and coastal farming inputs.",
      rating: 4.5,
      reviewCount: 98,
      openingHours: "Mon-Sat: 8:00 AM - 6:00 PM",
      distance: 480.2,
      imageUrl:
        "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w-800&auto=format&fit=crop",
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Smaller shops for variety
    {
      id: "shop_rui_001",
      name: "Ruiri Farmers Sacco Shop",
      address: "Ruiri Market, Meru",
      location: "Meru",
      latitude: 0.058056,
      longitude: 37.648056,
      phone: "+254711223344",
      category: "Cooperative",
      description:
        "Farmer-owned cooperative shop offering affordable inputs to members.",
      rating: 4.8,
      reviewCount: 67,
      openingHours: "Mon-Fri: 8:00 AM - 5:00 PM",
      distance: 190.3,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_kit_001",
      name: "Kitale Seed Distributors",
      address: "Kitale CBD, Trans Nzoia",
      location: "Trans Nzoia",
      latitude: 1.016667,
      longitude: 35.0,
      phone: "+254722334455",
      category: "Seeds",
      description:
        "Authorized distributor for Kenya Seed Company in Western Kenya.",
      rating: 4.7,
      reviewCount: 145,
      openingHours: "Mon-Sat: 7:30 AM - 6:00 PM",
      distance: 320.1,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    // --- ADDITIONAL SHOPS TO REACH 3 PER CATEGORY ---

    // Additional: Agricultural Supplies (already has 2, adding 1 more for good measure)
    {
      id: "shop_mac_001",
      name: "Machakos Farm Care",
      address: "Mbolu Malu Rd, Machakos",
      location: "Machakos",
      latitude: -1.517684,
      longitude: 37.263415,
      phone: "+254722000111",
      category: "Agricultural Supplies",
      description: "Everything you need for semi-arid farming.",
      rating: 4.4,
      reviewCount: 45,
      openingHours: "Mon-Sat: 8:00 AM - 6:00 PM",
      distance: 60.5,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: Seeds & Fertilizers (Needs 2 more)
    {
      id: "shop_nbi_004",
      name: "Nairobi Seeds Centre",
      address: "Kirinyaga Road, Nairobi",
      location: "Nairobi",
      latitude: -1.2841,
      longitude: 36.8255,
      phone: "+254733000222",
      category: "Seeds & Fertilizers",
      description: "Wide variety of vegetable and cereal seeds.",
      rating: 4.3,
      reviewCount: 112,
      openingHours: "Mon-Fri: 8:00 AM - 5:30 PM",
      distance: 1.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_kbu_003",
      name: "Kiambu Fertilizer Depot",
      address: "Kiambu Town Market",
      location: "Kiambu",
      latitude: -1.1714,
      longitude: 36.8277,
      phone: "+254733000333",
      category: "Seeds & Fertilizers",
      description: "Bulk fertilizers at wholesale prices.",
      rating: 4.6,
      reviewCount: 88,
      openingHours: "Daily: 7:00 AM - 6:00 PM",
      distance: 15.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: General Store (Needs 2 more)
    {
      id: "shop_nbi_005",
      name: "City General Farm Hardware",
      address: "Accra Road, Nairobi",
      location: "Nairobi",
      latitude: -1.2855,
      longitude: 36.8288,
      phone: "+254744000444",
      category: "General Store",
      description: "Farm tools, pipes, and general hardware.",
      rating: 4.2,
      reviewCount: 56,
      openingHours: "Mon-Sat: 8:00 AM - 6:00 PM",
      distance: 1.5,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_mur_001",
      name: "Muranga General Suppliers",
      address: "Uhuru Highway, Muranga",
      location: "Muranga",
      latitude: -0.721,
      longitude: 37.152,
      phone: "+254744000555",
      category: "General Store",
      description: "Serving the greater Muranga region.",
      rating: 4.5,
      reviewCount: 34,
      openingHours: "Mon-Sat: 7:30 AM - 5:30 PM",
      distance: 80.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: Farm Machinery (Needs 2 more)
    {
      id: "shop_eld_002",
      name: "Eldoret Tractors & Spares",
      address: "Industrial Area, Eldoret",
      location: "Uasin Gishu",
      latitude: 0.518,
      longitude: 35.273,
      phone: "+254755000666",
      category: "Farm Machinery",
      description: "Sales and service of tractors and implements.",
      rating: 4.8,
      reviewCount: 120,
      openingHours: "Mon-Fri: 8:00 AM - 5:00 PM",
      distance: 282.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_ksm_002",
      name: "Kisumu Agri-Machinery Ltd",
      address: "Obote Road, Kisumu",
      location: "Kisumu",
      latitude: -0.0917,
      longitude: 34.768,
      phone: "+254755000777",
      category: "Farm Machinery",
      description: "Heavy duty farm equipment leasing and sales.",
      rating: 4.6,
      reviewCount: 45,
      openingHours: "Mon-Fri: 8:00 AM - 5:00 PM",
      distance: 322.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: Veterinary Services (Needs 2 more)
    {
      id: "shop_nbi_006",
      name: "Karen Vet Clinic & Shop",
      address: "Langata Road, Karen",
      location: "Nairobi",
      latitude: -1.332,
      longitude: 36.705,
      phone: "+254766000888",
      category: "Veterinary Services",
      description: "Professional veterinary services and pet care products.",
      rating: 4.9,
      reviewCount: 210,
      openingHours: "Daily: 8:00 AM - 8:00 PM",
      distance: 15.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_kbu_004",
      name: "Limuru Animals Care",
      address: "Limuru Town",
      location: "Kiambu",
      latitude: -1.11,
      longitude: 36.64,
      phone: "+254766000999",
      category: "Veterinary Services",
      description: "Supporting dairy farmers in Limuru.",
      rating: 4.7,
      reviewCount: 65,
      openingHours: "Mon-Sat: 7:00 AM - 6:00 PM",
      distance: 30.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: Grains & Fertilizers (Needs 2 more)
    {
      id: "shop_nkr_003",
      name: "Nakuru Grain Depot",
      address: "Industrial Area, Nakuru",
      location: "Nakuru",
      latitude: -0.283,
      longitude: 36.066,
      phone: "+254777000111",
      category: "Grains & Fertilizers",
      description: "Bulk grains handling and storage.",
      rating: 4.5,
      reviewCount: 156,
      openingHours: "Mon-Sat: 8:00 AM - 5:00 PM",
      distance: 142.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_kit_002",
      name: "Kitale Produce Board",
      address: "Eldoret-Kitale Rd",
      location: "Trans Nzoia",
      latitude: 1.015,
      longitude: 35.005,
      phone: "+254777000222",
      category: "Grains & Fertilizers",
      description: "Your partner in maize farming.",
      rating: 4.6,
      reviewCount: 200,
      openingHours: "Mon-Sat: 7:00 AM - 6:00 PM",
      distance: 321.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: Fisheries & Aquaculture (Needs 2 more)
    {
      id: "shop_sag_001",
      name: "Sagana Fish Farm Supply",
      address: "Sagana, Kirinyaga",
      location: "Kirinyaga",
      latitude: -0.66,
      longitude: 37.2,
      phone: "+254788000333",
      category: "Fisheries & Aquaculture",
      description: "Fingerlings and fish feeds available.",
      rating: 4.8,
      reviewCount: 45,
      openingHours: "Mon-Sat: 8:00 AM - 5:00 PM",
      distance: 95.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_hom_001",
      name: "Homa Bay Aqua Shop",
      address: "Lake View, Homa Bay",
      location: "Homa Bay",
      latitude: -0.52,
      longitude: 34.45,
      phone: "+254788000444",
      category: "Fisheries & Aquaculture",
      description: "Serving Lake Victoria fishermen.",
      rating: 4.5,
      reviewCount: 32,
      openingHours: "Daily: 7:00 AM - 6:00 PM",
      distance: 360.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: Irrigation & Greenhouse (Needs 2 more)
    {
      id: "shop_nbi_007",
      name: "Amiran Kenya",
      address: "Old Airport North Rd, Nairobi",
      location: "Nairobi",
      latitude: -1.32,
      longitude: 36.88,
      phone: "+254799000555",
      category: "Irrigation & Greenhouse",
      description: "World class irrigation and greenhouse solutions.",
      rating: 4.9,
      reviewCount: 340,
      openingHours: "Mon-Fri: 8:00 AM - 5:00 PM",
      distance: 10.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_nai_001",
      name: "Naivasha Green Tech",
      address: "Moi South Lake Rd, Naivasha",
      location: "Nakuru",
      latitude: -0.72,
      longitude: 36.43,
      phone: "+254799000666",
      category: "Irrigation & Greenhouse",
      description: "Floriculture and horticulture specialists.",
      rating: 4.7,
      reviewCount: 150,
      openingHours: "Mon-Sat: 8:00 AM - 5:00 PM",
      distance: 90.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: Cooperative (Needs 2 more)
    {
      id: "shop_mer_001",
      name: "Meru Dairy Co-op Store",
      address: "Meru Town",
      location: "Meru",
      latitude: 0.04,
      longitude: 37.65,
      phone: "+254700111222",
      category: "Cooperative",
      description: "Dairy meal and minerals for members.",
      rating: 4.6,
      reviewCount: 89,
      openingHours: "Mon-Fri: 8:00 AM - 5:00 PM",
      distance: 195.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_mac_002",
      name: "Machakos Union Store",
      address: "Machakos Town",
      location: "Machakos",
      latitude: -1.52,
      longitude: 37.26,
      phone: "+254700111333",
      category: "Cooperative",
      description: "Coffee and general farming inputs.",
      rating: 4.4,
      reviewCount: 56,
      openingHours: "Mon-Fri: 8:00 AM - 5:00 PM",
      distance: 61.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },

    // Additional: Seeds (Needs 2 more)
    {
      id: "shop_nbi_008",
      name: "Simlaw Seeds Nairobi",
      address: "Kijabe Street, Nairobi",
      location: "Nairobi",
      latitude: -1.28,
      longitude: 36.82,
      phone: "+254711222333",
      category: "Seeds",
      description: "Top quality seeds for all seasons.",
      rating: 4.8,
      reviewCount: 180,
      openingHours: "Mon-Sat: 8:00 AM - 5:30 PM",
      distance: 0.8,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
    {
      id: "shop_kbu_005",
      name: "Royal Seed Stockist",
      address: "Banana Hill, Kiambu",
      location: "Kiambu",
      latitude: -1.2,
      longitude: 36.75,
      phone: "+254711222444",
      category: "Seeds",
      description: "Certified seeds dealer.",
      rating: 4.5,
      reviewCount: 40,
      openingHours: "Daily: 8:00 AM - 6:00 PM",
      distance: 12.0,
      verified: true,
      isActive: true,
      addedBy: "system",
      source: "local",
      ...getTimestamp(),
    },
  ];
};

// Run if called directly
if (require.main === module) {
  seedShops()
    .then(() => {
      console.log("🎉 Shop seeding completed!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("💥 Shop seeding failed:", error);
      process.exit(1);
    });
}

module.exports = { seedShops };
